### PR TITLE
Config with pure python

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by icemac** [comment]
I have no idea how to solve the problem with the dependency backtracking of pip. After adding some version pins so it does not try to install really old versions (and fail while doing so) it kept running for whole 6 hours before the job was killed by GHA.
Locally the problem cannot be reproduced. Probably because I am using an older version of `pip` there. (At least it complains that there is a new version.) — How do I get `tox` to use the current version of `pip`?

**Comment by icemac** [comment]
I already filled out the pip backtracking questionnaire linked in the output of GHA.

**Comment by jugmac00** [comment]
- I can reproduce the problem locally with tox (3)
- I cannot reproduce the problem locally with the upcoming tox4 (not sure how this relates to the dependency resolution)

> How do I get tox to use the current version of pip?

https://tox.readthedocs.io/en/latest/config.html#conf-download

(untested, as I always run the latest pip version locally anyway)

**Comment by jugmac00** [comment]
There is one thing I found out, which may or may not help you:

The problem does not exist for `pip install .` but only for `pip install .[test]`.

**Comment by icemac** [comment]
> The problem does not exist for `pip install .` but only for `pip install .[test]`.

Tox uses `/home/runner/work/grokcore.security/grokcore.security/.tox/py37/bin/python -m pip install --exists-action w -e '/home/runner/work/grokcore.security/grokcore.security[test]'` to install the package on GHA and the test extra is seems to be needed for successful tests.

**Comment by icemac** [comment]
Hm, tox 4 runs like a charm. So it seems like a problem between tox 3 and pip!?

**Comment by jugmac00** [comment]
Like I wrote in my previous comment, the issue is reproducable already with only `virtualenv` and `pip install .[test]` - so even with no `tox` involved.

So I think this is a `pip` issue with the dependency resolver, which you already reported :+1: 

Also, as this only happens when trying to install the `test` extras, this tells us two things:
- we can limit the problem to the test extras
- tox4 will be released at some time, and I would be fine with explicitly using tox4 here (and maybe wait for feedback from the pip team)

After I knew it is the test extras, I just removed one by one grok related package, and the culprit is `grok>1`

Just remove it, and the tox3 succeeds with all tests green - so this was an unnecessary dependency.

The tox3 vs tox4 difference will be unsolved, but I can live with it :-)

**Comment by icemac** [comment]
@jugmac00 Thank you for analyzing the problem!

**Comment by jugmac00** [comment]
@icemac Is there still a blocker why this has not been merged yet?

**Comment by icemac** [comment]
@jugmac00 I usually wait at least a week for a code review before merging a PR without a review.

**Comment by jugmac00** [comment]
> @jugmac00 I usually wait at least a week for a code review before merging a PR without a review.

Thank you! I completely missed that nobody found the time to review the changes.

I just stumbled upon it as I once again run tox4 on all Zope repos, and it hang with `grokcore.security` and I thought.. wait.. this has been fixed :-)

**Comment by icemac** [comment]
Thank you for the help with this PR. 😃

**Pull request merged**
